#this will run updates on the linux server and schedule a 2am reboot if needed
- name: OS Updates and Reboot
  hosts: webservers
  become: yes

  tasks:
    - name: Update Redhat
      when: ansible_os_family == 'RedHat'
      yum:
        name: '*'
        state: latest
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot at 2am
      ansible.builtin.command: shutdown -r 02:00
      when: reboot_required_file.stat.exists == true